# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-dynamic: true
linter:
  rules:
    unnecessary_brace_in_string_interps: false